@startuml
enum ngk.devtools.proto.Payment {
	CASH,
	CREDIT_CARD,
	DEBIT_CARD,
	APP
}
class ngk.devtools.proto.Person {
	name: string,
	lastname: string,
	address: List<Address>,
	addresses: Map<string,Address>,
	> afm: string,
	> amka: string,
	paymentMethod: Payment
}
class ngk.devtools.proto.Address {
	country: string,
	city: string,
	street: string,
	number: string,
	zipCode: string
}
Person::address -> Address
Person::addresses -> Address
Person::paymentMethod -> Payment
hide empty methods
@enduml