@startuml
class ngk.devtools.proto.Person {
	name: string,
	lastname: string,
	address: List<Address>,
	addresses: Map<string,Address>
}
class ngk.devtools.proto.Address {
	country: string,
	city: string,
	street: string,
	number: string,
	zipCode: string
}
Person::address -> Address
Person::addresses -> Address
hide empty methods
@enduml